image: node:latest

stages:
#    - deps
    - build

cache:
    paths:
        - .npm/

#install:
#    stage: deps
#    script:
#        - npm ci --cache .npm --prefer-offline

runbuild:
    stage: build
    script:
        - npm run build